### ISSUE TITLE
Add Vale style linter

### ISSUE THREAD

**Issue by hawkeyexl** [doc-detective/doc-detective.github.io#42]
vale.sh is a wonderful style linter. While we need to define our own style, getting Vale integrated with something basic is the first step.

**Comment by theiiienrique** [comment]
hi @hawkeyexl, I'd like to take on this issue! were there any particular [base/supplementary styles](https://vale.sh/generator) you wanted to use?

**Comment by hawkeyexl** [comment]
Hi @theiiienrique, the ticket is yours! Thank you.

Let's go with the Google Developer Style guide, Alex, and joblint. Curious how much overlap there is between those, but that should give us a good starting point.
